### ISSUE TITLE
Mining over privacy network (Tor/i2p) setting

### ISSUE THREAD

**Issue by CryptoGrampy** [hinto-janai/gupax#32]
Would it be possible to add a simple setting for Gupax to run P2Pool / Mine over i2p or Tor?   It would be great to see this software as resilient as possible for areas where it may be dangerous to be running p2pool software.

**Comment by hinto-janai** [comment]
Gupax has a Tor client inside but not a server. It can create circuits, connect to them, send/recv bytes via that circuit, but it can't forward arbitrary bytes from a different process. 

Although, that part can be added. P2Pool also can natively connect to a SOCKS proxy which makes it easier.

I didn't add this initially because of the downside of using a latency-heavy connection to mine on a latency-sensitive pool like P2Pool. In the case of remote nodes, you can negate this by picking a fast node close to you, but with Tor, the nodes you get routed through are random (technically, you can manually pick your circuit but that's... a bad idea).

A circuit that takes 5 seconds from `You -> Tor -> P2Pool` and back means all your blocks will be  stale.
