### ISSUE TITLE
2 machines with the same wallet set up - only one reporting payouts

### ISSUE THREAD

**Issue by spiritblackhole** [hinto-janai/gupax#4]
As per the title - is this normal behaviour?

**Comment by hinto-janaiyo** [comment]
They should both be reporting payouts/XMR mined but only shares are only reported on the P2Pool that found them.

**Comment by spiritblackhole** [comment]
Here's the stats for both workers - just trying to determine is this is normal:
https://imgur.com/a/hwOK6Ex

**Comment by hinto-janaiyo** [comment]
Hmm... interesting, that isn't normal. If they are both using the same address and were started at around the same time then yes, they _should_ be showing the same payouts/XMR. What exactly is the setup? Are the stats inline with [`p2pool.observer`](https://p2pool.observer)?

Not a solution but you could point the 2nd XMRig at the 1st P2Pool instead of running two.

**Comment by spiritblackhole** [comment]
Ok, interesting... p2pool.observer is not finding my payout address at all. Not sure what's going on there.

The setup is simply 2 windows pcs on the same lan, both running gupax with the same monero wallet address. They're connected to different nodes.

**Comment by hinto-janaiyo** [comment]
Ah right, if you're using default Gupax settings you're on mini: [`mini.p2pool.observer`](https://mini.p2pool.observer)

Actually, this might be why there are different stats, are you using `Simple` for both P2Pools? Main and Mini are different sidechains so even with the same address, the shares/payouts are different.

**Comment by spiritblackhole** [comment]
Got it. I can see stats for my wallet on mini.p2pool.observer.

Both Gupax instances have the same config. All set to Simple, all default values under the hood. Maybe this is the reason only one is reporting, because everything is identical?

**Comment by hinto-janaiyo** [comment]
P2Pool itself will report the same payouts on multiple instances and since Gupax relays P2Pool's stats, it _should_ be showing it across multiple instances as well.

Can you enter the `status` command for both P2Pools in `P2Pool Advanced` and see if their internal stats are matching? Ideally when you get a payout so you can compare.

**Comment by spiritblackhole** [comment]
Ok, curious - the commands are not doing anything (status -> enter -> nothing happens, just the usual log flow).

I've restarted Gupax to make sure and it's still like this. Also, Gupax isn't automatically pinging/connecting on start, despite checkboxes set to do that.

**Comment by hinto-janaiyo** [comment]
The `status` output will show in the log.

Not sure about the auto-ping, it seems to work fine in my Windows VM.

**Comment by hinto-janaiyo** [comment]
>the commands are not doing anything

Ok, this is actually a bug. Commands don't seem to work on Windows, will fix next release.

**Comment by spiritblackhole** [comment]
Happy to help troubleshoot!

I'll be switching the miners to Linux shortly but it's great to have a choice of platforms.

**Comment by hinto-janaiyo** [comment]
@spiritblackhole

The Windows commands are now [fixed.](https://github.com/hinto-janaiyo/gupax/releases/tag/v1.1.2)
