### ISSUE TITLE
Add option to join and donate to XMRvsBeast raffle

### ISSUE THREAD

**Issue by snex** [hinto-janai/gupax#76]
**Feature request**

XMRvsBeast generously operates a bonus raffle over at https://xmrvsbeast.com/p2pool/

It would be cool if joining this as well as donating hashrate could be automated via Gupax. The more people donate, the bigger the rewards are for winners.

**Comment by snex** [comment]
You never have to donate in order to win the "normal" rounds. It is just free hash rate if you do win. You just have to register your address. If you choose to donate, you have more chances to win. XMRvsBeast is not another pool - it is a part of p2pool just like Gupax users are. You do have to trust that he rewards people fairly, but he has been doing so for several years now.

**Comment by elstak80** [comment]
Well, will be great to have a flag to donate (not the VIP) and also to select how many threads use for the donation... will be easier for the ppl to donate. Gupax can show 2 xmrig's windows...

**Comment by Cyrix126** [comment]
Hello,
For reference I'm made a [fork](https://github.com/Cyrix126/gupaxx) (beta is released) to integrate the XvB raffle as to complete this [bounty](https://bounties.monero.social/posts/105).

**Comment by Rikj000** [comment]
@Cyrix126, I noticed the bounty has been completed, thank you for your work!

Do you intend to send a PR to Gupax to merge in with upstream?   
Or will Gupaxx remain a separate fork?   
If the latter is true, can we expect that you will keep your fork up-to-date with upstream changes?

**Comment by Cyrix126** [comment]
> @Cyrix126, I noticed the bounty has been completed, thank you for your work!
> 
> Do you intend to send a PR to Gupax to merge in with upstream? Or will Gupaxx remain a separate fork? If the latter is true, can we expect that you will keep your fork up-to-date with upstream changes?

Gupax was originally  funded by CCS which included maintenance lasting for end of 2023. Since then updates were mostly some bugfixes and keeping the list of nodes updated.
I don't know if @hinto-janai plans to update it more. Like I explain in [DIFFERENCES](https://github.com/Cyrix126/gupaxx/blob/main/DIFFERENCES.md) there are more issues that are fixed in my fork. 
I'm pretty sure he is [busy working on Cuprate](https://github.com/Cuprate/cuprate/commits/main/?author=hinto-janai) right now.
Proposing a PR at this point would be a lot of work, because I completely refactored the code. I plan however to keep Gupaxx up to date in the case upstream brings new commits.
You can see [ideas](https://github.com/Cyrix126/gupaxx/blob/main/IDEAS.md) that are thoughts for Gupaxx (subject to change).

**Comment by hinto-janai** [comment]
@Cyrix126 thanks for ping.

> I'm pretty sure he is busy working on Cuprate right now.

Sorry about this, I haven't had much time to touch any other repo for the past few months.

> Proposing a PR at this point would be a lot of work, because I completely refactored the code. I plan however to keep Gupaxx up to date in the case upstream brings new commits.

I have to say I'm impressed with Gupaxx, if I could re-write this project, I would have made many of the changes you've made.

If you want, you could rename your project and make it your own; I don't plan to add features, mostly bug fixes and node updates, so I think staying connected to upstream may hold back Gupaxx development.

**Comment by Cyrix126** [comment]
Thank you for your kind words, I have to say it was a pleasure understanding your code with all the good documentation you made.

> If you want, you could rename your project and make it your own

I'm willing to take the maintenance, should we discuss it in details over matrix ?

**Comment by hinto-janai** [comment]
`@hinto:monero.social` - what is your ID?

**Comment by Cyrix126** [comment]
sent you an invite.
